### ISSUE TITLE
tmap_save failed to run example code

### ISSUE THREAD

**Issue by jakemkc** [mtennekes/tmap#356]
Hi,

A few months ago, I needed to create US map with Hawaii and Alaska insets, so I took reference from the code for Figure 11 (https://cran.r-project.org/web/packages/tmap/vignettes/tmap-JSS-code.html). It worked flawlessly. 

Today I tried to use tmap (updated to 2.3 and 2.3-1) and rerun the code. In the last step running tmap_save, version 2.3 is returning error:  
"Error: Specify at least one layer after each tm_shape"

version 2.3-1 is returning error: 
"Error: Fill argument neither colors nor valid variable name(s)
In addition: Warning message:
In data.frame(..., check.names = FALSE) :
  row names were found from a short variable and have been discarded"

I have to down grade to tmap version 2.1-1 to get it running.

Is that a bug or tmap_save should be run differently in latest version?

Best,
Jake

**Comment by Nowosad** [comment]
Just for a reference - the code giving the error:

```r

## install.packages(c("tmap", "tmaptools"))
library("tmap") # required version 2.0 or later
library("tmaptools") # required version 2.0 or later
#############################
library("readxl")
library("grid")

data("World", "metro", package = "tmap")
metro$growth <- (metro$pop2020 - metro$pop2010) / (metro$pop2010 * 10) * 100

# function to obtain US county shape
get_US_county_2010_shape <- function() {
  dir <- tempdir()
  download.file("http://www2.census.gov/geo/tiger/GENZ2010/gz_2010_us_050_00_20m.zip", destfile = file.path(dir, "gz_2010_us_050_00_20m.zip"))
  unzip(file.path(dir, "gz_2010_us_050_00_20m.zip"), exdir = dir)
  US <- sf::read_sf(file.path(dir, "gz_2010_us_050_00_20m.shp"))
  levels(US$NAME) <- iconv(levels(US$NAME), from = "latin1", to = "utf8")
  US
}

US <- get_US_county_2010_shape()

#############################
## Figure 11
#############################
US_cont <- US %>% 
  subset(!STATE %in% c("02", "15", "72")) %>% 
  simplify_shape(0.2) 

US_AK <- US %>% 
  subset(STATE == "02") %>% 
  simplify_shape(0.2) 

US_HI <- US %>% 
  subset(STATE == "15") %>% 
  simplify_shape(0.2) 

# create state boundaries
US_states <- US_cont %>% 
  dplyr::select(geometry) %>% 
  aggregate(by = list(US_cont$STATE), FUN = mean)


# contiguous US
m_cont <- tm_shape(US_cont, projection = 2163) +
  tm_polygons("PCT_OBESE_ADULTS10", border.col = "gray50", border.alpha = .5, title = "", showNA = TRUE) +
  tm_shape(US_states) +
  tm_borders(lwd = 1, col = "black", alpha = .5) +
  tm_credits("Data @ Unites States Department of Agriculture\nShape @ Unites States Census Bureau", position = c("right", "bottom")) +
  tm_layout(title = "2010 Adult Obesity by County, percent", 
            title.position = c("center", "top"), 
            legend.position = c("right", "bottom"), 
            frame = FALSE, 
            inner.margins = c(0.1, 0.1, 0.05, 0.05))

# Alaska inset
m_AK <- tm_shape(US_AK, projection = 3338) +
  tm_polygons("PCT_OBESE_ADULTS10", border.col = "gray50", border.alpha = .5, breaks = seq(10, 50, by = 5)) +
  tm_layout("Alaska", legend.show = FALSE, bg.color = NA, title.size = 0.8, frame = FALSE)

# Hawaii inset
m_HI <- tm_shape(US_HI, projection = 3759) +
  tm_polygons("PCT_OBESE_ADULTS10", border.col = "gray50", border.alpha = .5, breaks = seq(10, 50, by = 5)) +
  tm_layout("Hawaii", legend.show = FALSE, bg.color = NA, title.position = c("LEFT", "BOTTOM"), title.size = 0.8, frame = FALSE)

# specify viewports for Alaska and Hawaii
vp_AK <- viewport(x = 0.15, y = 0.15, width = 0.3, height = 0.3)
vp_HI <- viewport(x = 0.4, y = 0.1, width = 0.2, height = 0.1)

# save map
tmap_mode("plot")
tmap_save(m_cont, "USchoro.png", scale = 0.7, width = 6.125, outer.margins = 0,
          insets_tm = list(m_AK, m_HI), 
          insets_vp = list(vp_AK, vp_HI))

```

**Comment by mtennekes** [comment]
This bug should be fixed now. Could you please double-check @jakemkc (or @Nowosad)?

**Comment by Nowosad** [comment]
Works now:

``` r
# library(devtools)
# install_github("mtennekes/tmaptools")
# install_github("mtennekes/tmap")

## install.packages(c("tmap", "tmaptools"))
library(tmap) # required version 2.0 or later
library(tmaptools) # required version 2.0 or later
#############################
library(readxl)
library(grid)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0

data("World", "metro", package = "tmap")
metro$growth <- (metro$pop2020 - metro$pop2010) / (metro$pop2010 * 10) * 100

# function to obtain Food Environment Atlas data (2014)
get_food_envir_data <- function() {
  dir <- tempdir()
  if (!file.exists(file.path(dir, "DataDownload.xls"))) {
    download.file("https://www.ers.usda.gov/webdocs/DataFiles/48731/February2014.xls?v=41688", destfile = file.path(dir, "DataDownload.xls"), mode = "wb")
  }
  res <- tryCatch({
    read_excel(file.path(dir, "DataDownload.xls"), sheet = "HEALTH")    
  }, error = function(e) {
    stop("The excel file cannot be read. Please open it, and remove all sheets except HEALTH. The location of the file is: ", normalizePath(file.path(dir, "DataDownload.xls")))
  })
}

# function to obtain US county shape
get_US_county_2010_shape <- function() {
  dir <- tempdir()
  download.file("http://www2.census.gov/geo/tiger/GENZ2010/gz_2010_us_050_00_20m.zip", destfile = file.path(dir, "gz_2010_us_050_00_20m.zip"))
  unzip(file.path(dir, "gz_2010_us_050_00_20m.zip"), exdir = dir)
  US <- sf::read_sf(file.path(dir, "gz_2010_us_050_00_20m.shp"))
  levels(US$NAME) <- iconv(levels(US$NAME), from = "latin1", to = "utf8")
  US
}
# obtain Food Environment Atlas data
FEA <- get_food_envir_data()

# obtain US county shape
US <- get_US_county_2010_shape()

US$FIPS <- paste0(US$STATE, US$COUNTY)

# append data to shape
#US <- append_data(US, FEA, key.shp = "FIPS", key.data = "FIPS", ignore.duplicates = TRUE)
US <- left_join(US, FEA, by = c("FIPS", "FIPS"))

#############################
## Figure 11
#############################
US_cont <- US %>% 
  subset(!STATE %in% c("02", "15", "72")) %>% 
  simplify_shape(0.2) 
#> Registered S3 method overwritten by 'geojsonlint':
#>   method         from 
#>   print.location dplyr

US_AK <- US %>% 
  subset(STATE == "02") %>% 
  simplify_shape(0.2) 

US_HI <- US %>% 
  subset(STATE == "15") %>% 
  simplify_shape(0.2) 

# create state boundaries
US_states <- US_cont %>% 
  dplyr::select(geometry) %>% 
  aggregate(by = list(US_cont$STATE), FUN = mean)


# contiguous US
m_cont <- tm_shape(US_cont, projection = 2163) +
  tm_polygons("PCT_OBESE_ADULTS10", border.col = "gray50", border.alpha = .5, title = "", showNA = TRUE) +
  tm_shape(US_states) +
  tm_borders(lwd = 1, col = "black", alpha = .5) +
  tm_credits("Data @ Unites States Department of Agriculture\nShape @ Unites States Census Bureau", position = c("right", "bottom")) +
  tm_layout(title = "2010 Adult Obesity by County, percent", 
            title.position = c("center", "top"), 
            legend.position = c("right", "bottom"), 
            frame = FALSE, 
            inner.margins = c(0.1, 0.1, 0.05, 0.05))

# Alaska inset
m_AK <- tm_shape(US_AK, projection = 3338) +
  tm_polygons("PCT_OBESE_ADULTS10", border.col = "gray50", border.alpha = .5, breaks = seq(10, 50, by = 5)) +
  tm_layout("Alaska", legend.show = FALSE, bg.color = NA, title.size = 0.8, frame = FALSE)

# Hawaii inset
m_HI <- tm_shape(US_HI, projection = 3759) +
  tm_polygons("PCT_OBESE_ADULTS10", border.col = "gray50", border.alpha = .5, breaks = seq(10, 50, by = 5)) +
  tm_layout("Hawaii", legend.show = FALSE, bg.color = NA, title.position = c("LEFT", "BOTTOM"), title.size = 0.8, frame = FALSE)

# specify viewports for Alaska and Hawaii
vp_AK <- viewport(x = 0.15, y = 0.15, width = 0.3, height = 0.3)
vp_HI <- viewport(x = 0.4, y = 0.1, width = 0.2, height = 0.1)

# save map
tmap_mode("plot")
#> tmap mode set to plotting
tmap_save(m_cont, "USchoro.png", scale = 0.7, width = 6.125, outer.margins = 0,
          insets_tm = list(m_AK, m_HI), 
          insets_vp = list(vp_AK, vp_HI))
#> Map saved to /tmp/RtmpLypgdL/reprex134c377bd31c/USchoro.png
#> Resolution: 1837.5 by 1150.636 pixels
#> Size: 6.125 by 3.835454 inches (300 dpi)
```

<sup>Created on 2019-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jakemkc** [comment]
It still not working for me after installing the latest github version (still named 2.3-1)

Here is the error:
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 227, 228
Called from: data.frame(..., check.names = FALSE)
Browse[1]> Q

I guess something is wrong in my plotting dataframe and will double check. Now I will keep using the older version.

Jake
