### ISSUE TITLE
Control width of popup.vars text box in tm_polygons

### ISSUE THREAD

**Issue by NickPyll** [mtennekes/tmap#450]
Look at the map here https://rpubs.com/Pyll/617676 for an example of what I'm talking about. Is there a way to control the width of the box so the text can fit properly?

**Comment by mtennekes** [comment]
Should have been fixed in this commit: https://github.com/mtennekes/tmap/commit/e87d8fa09854ce7fb913a145666d12419c1bb8e0
Could you check if it works? Please reopen if necessary.

**Comment by NickPyll** [comment]
Just installed the dev version, because I was using CRAN and still not looking like it will autosize. Am I doing something wrong?

```
mymap <- 
  tm_shape(x.data) +
  tm_polygons('census_response_rate',
              alpha = .7,
              palette = colscale,
              border.col = "white", 
              border.alpha = 0.5,
              title = "Response (%)",
              id = 'label',
              popup.vars = c("Response (%)"="census_response_rate",
                             "Population"="total_pop_dist",
                             "African-American (%)"="pct_aa_pop",
                             "Annual Change in HPI (%)"="annual_change")) +
  tm_shape(food.desert_sf) +
  tm_borders("grey40", lwd = 2) +
  tm_layout(title = "Census response rate by census tract",
            title.size = 1.1,
            title.position = c("center", "top"))

# saveWidget(mymap, "census-map-example.html")

mymap

```

**Comment by NickPyll** [comment]
Here is a reproducible example. How can we get the entry on one line?

```
data("World")

tm_shape(World) +
  tm_polygons("HPI",
              popup.vars = c("Estimated Population"="pop_est"))
```

**Comment by NickPyll** [comment]
Posted to SO [here](https://stackoverflow.com/questions/62030531/control-width-of-popup-in-tmap-r), we'll see if the SO community can help. If not, I may have to reopen as I'm not sure what I'm doing wrong.  Thanks for help.

**Comment by mtennekes** [comment]
Don't think people on SO can help you more than here;-)

Are you sure you don't have the latest github version? It works here (Ubuntu 20.04 / R4.0):

![Screenshot from 2020-05-27 07-42-50](https://user-images.githubusercontent.com/2444081/82982098-b6227b00-9fed-11ea-9753-b0739436b1de.png)

And also in the browser (Firefox and Chrome).

**Comment by NickPyll** [comment]
Facepalm... I was using tmap v3.0. upgraded to 3.1 and I'm in business.

Thanks for the patience, and the help.
