### ISSUE TITLE
default graticules with tm_facet

### ISSUE THREAD

**Issue by smwoodman** [mtennekes/tmap#453]
Apologies if I missed documentation about this somewhere, but could the default behavior of tm_graticule be changes when used with tm_facet? Specifically, could the tick marks and labels only be present on the outer edges of the specified sides? I feel this would make for a cleaner map with less wasted whitespace. Examples of current and desired behavior below:

tmap facet without graticules - great!

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(tmap)

nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
nc4 <- bind_rows(
  cbind(nc, year = 1), cbind(nc, year = 2), 
  cbind(nc, year = 3), cbind(nc, year = 4)
)

tm.nc <- tm_shape(nc4) + 
  tm_fill(col = "AREA") + 
  tm_facets(by = c("year"), nrow = 2, ncol = 2, 
            free.coords = FALSE, free.scales = FALSE) +
  tm_legend(outside = TRUE, position = c("right", "center"), outside.size = 0.2)

tm.nc
```

![](https://i.imgur.com/7Si9Szr.png)

tmap default facet with graticules

``` r
tm.nc +
  tm_graticules(ticks = TRUE, lines = FALSE, n.y = 5, n.x = 5, labels.size = 1)
```

![](https://i.imgur.com/vgOSkSC.png)

Desired output format with facet and graticules

``` r
ggplot(data = st_transform(nc4, 4326)) + 
  geom_sf(aes(fill = AREA)) + 
  facet_wrap(vars(year), nrow = 2) + 
  coord_sf(crs = 4326, label_graticule = "SW")
```

![](https://i.imgur.com/5VjWeLq.png)

<sup>Created on 2020-06-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
Fixed. Thx!

**Comment by smwoodman** [comment]
Thank you! However, when I run the above code with the developmental version of tmap, I 1) still get the above plots (with the tick marks on all of the facet plots) and 2) now get 8 of the following warning messages when running `tm.nc +  tm_graticules(ticks = TRUE, lines = FALSE, n.y = 5, n.x = 5, labels.size = 1)`:

```{r}
Warning messages:
1: In st_cast.sf(lns, "LINESTRING") :
  repeating attributes for all sub-geometries for which they may not be constant
```

I'm not sure if there's additional arguments that should be passed to tm_facet and tm_graticules, or.?

**Comment by mtennekes** [comment]
I was working on other issues with graticules, but now it should be working again. Please let me know if you encounter other problems.

**Comment by smwoodman** [comment]
Hm, I still have the same behavior with the above examples even with the latest tmap developmental version

**Comment by mtennekes** [comment]
You mean incorrect graticule ticks/labels? Or the warnings?
Probably, you'll need the dev version of tmaptools too.

**Comment by smwoodman** [comment]
Sorry that wasn't very clear on my part. I meant that when plotting the ticks/labels while also using tm_facets, I was hoping for the output to look like the ggplot2 output, meaning that x axis ticks and labels would only be on the bottom row of panels, while y axis ticks and labels would only be on the left column of panels. But I still see the following when using the dev versions of both:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(tmap)

sessionInfo()
#> R version 4.0.0 (2020-04-24)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 18363)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] tmap_3.1    sf_0.9-3    dplyr_1.0.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.4.6       pillar_1.4.4       compiler_4.0.0     RColorBrewer_1.1-2
#>  [5] highr_0.8          base64enc_0.1-3    class_7.3-17       tools_4.0.0       
#>  [9] digest_0.6.25      viridisLite_0.3.0  lattice_0.20-41    evaluate_0.14     
#> [13] lifecycle_0.2.0    tibble_3.0.1       png_0.1-7          pkgconfig_2.0.3   
#> [17] rlang_0.4.6        DBI_1.1.0          crosstalk_1.1.0.1  parallel_4.0.0    
#> [21] yaml_2.2.1         xfun_0.14          e1071_1.7-3        raster_3.1-5      
#> [25] stringr_1.4.0      knitr_1.28         generics_0.0.2     vctrs_0.3.1       
#> [29] htmlwidgets_1.5.1  classInt_0.4-3     leaflet_2.0.3      grid_4.0.0        
#> [33] tidyselect_1.1.0   glue_1.4.1         R6_2.4.1           XML_3.99-0.3      
#> [37] rmarkdown_2.2      sp_1.4-2           purrr_0.3.4        magrittr_1.5      
#> [41] scales_1.1.1       codetools_0.2-16   tmaptools_3.0-1    stars_0.4-1       
#> [45] ellipsis_0.3.1     htmltools_0.4.0    leafsync_0.1.0     units_0.6-6       
#> [49] dichromat_2.0-0    abind_1.4-5        colorspace_1.4-1   KernSmooth_2.23-17
#> [53] stringi_1.4.6      munsell_0.5.0      leafem_0.1.1       lwgeom_0.2-4      
#> [57] crayon_1.3.4

nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
nc4 <- bind_rows(
  cbind(nc, year = 1), cbind(nc, year = 2), 
  cbind(nc, year = 3), cbind(nc, year = 4)
)

# Graticules appear on all plots
tm_shape(nc4) + 
  tm_fill(col = "AREA") + 
  tm_facets(by = c("year"), nrow = 2, ncol = 2, 
            free.coords = FALSE, free.scales = FALSE) +
  tm_legend(outside = TRUE, position = c("right", "center"), outside.size = 0.2) +
  tm_graticules(ticks = TRUE, lines = FALSE, n.y = 5, n.x = 5, labels.size = 1)
```

![](https://i.imgur.com/xv2v4Fv.png)

<sup>Created on 2020-06-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
