### ISSUE TITLE
R tmap: polygons plotted in tmap_mode(“view”) but  only the first observation with (“plot”)

### ISSUE THREAD

**Issue by bertagrau** [mtennekes/tmap#545]
I am trying to plot a polygon with `tmap`  r package. 

My object comes from a shapefile, and looks like: 

``` Simple feature collection with 261 features and 7 fields
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: 453850.6 ymin: 7168979 xmax: 513813.6 ymax: 7234603
CRS:            +proj=utm +zone=36 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs
First 10 features:
   NeighCode  NameNeigh   Locality AdminPost Populacao Shape_Leng Shape_Area                       geometry
1       3914    Bassane Chichongue   Calanga       114  41926.454  111037471 POLYGON ((504325.3 7212444,...
2       3913 Chinguwine Chichongue   Calanga       181  16966.423   14526253 POLYGON ((499974.9 7212379,...
3       3912   Sihanine Chichongue   Calanga       238  13508.601    9502638 POLYGON ((500542.6 7208832,...
4       3911    Mpalene Chichongue   Calanga       352   6961.326    2646152 POLYGON ((499063.9 7208412,...
5       3910 Chichongue Chichongue   Calanga       342  12096.768    6473003 POLYGON ((498551.8 7206144,...

```

When I am trying to plot it with `plot()`, I get this: 

![District plot][1]

But, when I am doint it with `tmap` with the following code: 
```
dss_map <- tm_shape(dss_utm) + 
  tm_polygons("AdminPost") + 
  tm_layout(frame = F)
dss_map
```

I get [District plot with tmap_mode("plot")][2] with `tmap_mode("plot")`. Only the first observation is plotted. With `tmap_mode("view")` all of them are plotted. 

Anyone could tell me what is happening? I could plot this object in `tmap_mode("plot")` before without any problems. Here is a link (https://stackoverflow.com/questions/64380204/tmap-only-plotting-first-polygon-in-sf-geometry-column/66007622?noredirect=1#comment116705656_66007622/) of a similar question that wasn't answered. 

Thanks for your help!

  [1]: https://i.stack.imgur.com/FQsjW.jpg
  [2]: https://i.stack.imgur.com/QqskU.jpg

**Comment by Nowosad** [comment]
Hi @bertagrau, 
is it possible that your polygons has some invalid parts?
Could you let us know what happens when you type `st_is_valid(your_object)`? 
Also, could you try to make your object valid before plotting:

```r
my_object = st_make_valid(my_object)
```

**Comment by bertagrau** [comment]
Thanks @Nowosad 

I tried and all of them are valid. All appear as `TRUE`. 

After `my_object = st_make_valid(my_object)` only one geometry is still plotted.

**Comment by Nowosad** [comment]
Could you share this dataset with us?

**Comment by bertagrau** [comment]
Yes, @Nowosad. How do you normally do it? In which format?

**Comment by Nowosad** [comment]
Either .gpkg or .rds should be fine. You can zip it and upload it here.

**Comment by bertagrau** [comment]
Find it here! Thanks! 
[dss_git.zip](https://github.com/mtennekes/tmap/files/5912354/dss_git.zip)

**Comment by Nowosad** [comment]
I cannot reproduce your issue (see below). Maybe this bug was already fixed in **tmap**. Have you tried updating **tmap**?

```r
library(remotes)
install_github("mtennekes/tmaptools")
install_github("mtennekes/tmap")
```

``` r
library(tmap)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.2

of = tempfile("dss_git.zip")
od = tempdir()
download.file("https://github.com/mtennekes/tmap/files/5912354/dss_git.zip", of)
unzip(of, exdir = od)

x = readRDS(paste0(od, "/dss_git.rds"))
x
#> Simple feature collection with 261 features and 3 fields
#> geometry type:  POLYGON
#> dimension:      XY
#> bbox:           xmin: 453850.6 ymin: 7168979 xmax: 513813.6 ymax: 7234603
#> CRS:            +proj=utm +zone=36 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs
#> First 10 features:
#>    region   Locality AdminPost                       geometry
#> 1    3914 Chichongue   Calanga POLYGON ((504325.3 7212444,...
#> 2    3913 Chichongue   Calanga POLYGON ((499974.9 7212379,...
#> 3    3912 Chichongue   Calanga POLYGON ((500542.6 7208832,...
#> 4    3911 Chichongue   Calanga POLYGON ((499063.9 7208412,...
#> 5    3910 Chichongue   Calanga POLYGON ((498551.8 7206144,...
#> 6    3909 Chichongue   Calanga POLYGON ((499479.5 7203926,...
#> 7    3908 Chichongue   Calanga POLYGON ((500852.8 7203791,...
#> 8    3916 Chichongue   Calanga POLYGON ((502661.6 7202054,...
#> 9    3917 Lagoa Pate   Calanga POLYGON ((509652.8 7200495,...
#> 10   3918 Lagoa Pate   Calanga POLYGON ((507646.7 7197057,...

# works
plot(x)            
```

![](https://i.imgur.com/OtEyqCr.png)

``` r
# works
qtm(x)
```

![](https://i.imgur.com/JT70WqL.png)

``` r
# works
tm_shape(x) +
  tm_polygons("region")
#> Warning: Number of levels of the variable "region" is 256, which is
#> larger than max.categories (which is 30), so levels are combined. Set
#> tmap_options(max.categories = 256) in the layer function to show all levels.
```

![](https://i.imgur.com/1x62FCX.png)

<sup>Created on 2021-02-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by bertagrau** [comment]
I it very weird. 

I removed and installed `tmap` and `tmaptools`. Now in version 3.3 and 3.1.1 respectively. But I am still getting the same plot with both `qtm()` and 
```
tm_shape(x) +
  tm_polygons("region")
```
What should that be?

**Comment by Nowosad** [comment]
The same means that you still just get one polygon? Have you restarted your R session? What's your R version?

**Comment by bertagrau** [comment]
It was that! I updated the last R version and now it works. Maybe it was a bug already corrected. 

Thanks so much @Nowosad!
